# Emoji fallback for Kitty
symbol_map U+1F000-U+1FAFF Noto Color Emoji


# Font
font_family JetBrainsMono Nerd Font
font_size 10.0

# Window opacity
background_opacity 0.5

# Colors (fallback in case pywal file isn't found)
background #c1c0c0
foreground #090404
cursor     #c1c0c0

color0 #090404
color1 #3B6440
color2 #546F56
color3 #648C63
color4 #7E9981
color5 #91AA92
color6 #B3C7B3
color7 #c1c0c0
color8 #665353
color9 #3B6440
color10 #546F56
color11 #648C63
color12 #7E9981
color13 #91AA92
color14 #B3C7B3
color15 #c1c0c0

symbol_map U+1F300-U+1F5FF,U+1F900-U+1F9FF,U+1FA70-U+1FAFF,U+1F600-U+1F64F,U+2600-U+26FF,U+2700-U+27BF Noto Color Emoji

[window.class]
instance = "cava"
general = "cava"

# Import pywal colors after the fallback palette.
include /home/tanmay/.cache/wal/colors-kitty.conf
