#wofi
bind = SUPER, A, exec, wofi --show drun

#kill app
bind = SUPER,Q, killactive

# SUPER + T -> Terminal (Alacritty)
bind = SUPER, T, exec, kitty

# SUPER + E -> Dolphin File Manager
bind = SUPER, E, exec, thunar

# SUPER + B -> Brave Browser
bind = SUPER, B, exec, brave

# SUPER + V -> VSCode
bind = SUPER, V, exec, code

#cursor
bind = SUPER, C, exec, cursor

#warp
bind = SUPER, W, exec, warp-terminal

# SUPER + M -> System Monitor
bind=SUPER,M,exec,/usr/bin/foot btop

#lock screen
bind = SUPER,L, exec, hyprlock --config ~/.config/hyprlock/hyprlock.conf

#kdenlive
bind = SUPER, K, exec, /usr/bin/kdenlive

#sleep
bind = SUPER, ESCAPE, exec, systemctl suspend


# Screenshot of selected region with PrintScreen
bind = SHIFT, Print, exec, grim -g "$(slurp)" - | wl-copy && wl-paste > /home/tanmay/Videos/Captures/Screenshot-$(date +%F_%H-%M-%S).png && notify-send "📸 Region screenshot saved!"

# Screenshot of full screen with Shift + PrintScreen
bind = , Print, exec, grim - | wl-copy && wl-paste > /home/tanmay/Videos/Captures/Screenshot-$(date +%F_%H-%M-%S).png && notify-send "🖥️ Fullscreen screenshot saved!"

#text-exctrator
bind = SUPER SHIFT, T, exec, ~/.config/OCR4Linux/OCR4Linux.sh



# Brightness
bind=,XF86MonBrightnessDown,exec,~/.config/hypr/brightness-volume.sh brightness 2%-
bind=,XF86MonBrightnessUp,exec,~/.config/hypr/brightness-volume.sh brightness 2%+

# Volume
bind=,XF86AudioLowerVolume,exec,~/.config/hypr/brightness-volume.sh volume -5%
bind=,XF86AudioRaiseVolume,exec,~/.config/hypr/brightness-volume.sh volume +5%

# Mute
bind=,XF86AudioMute,exec,~/.config/hypr/brightness-volume.sh mute



#kooha

bind = SUPER, O, exec, flatpak run io.github.seadve.Kooha

#color-extractor
bind = SUPER, P, exec, hyprpicker -a

